FROM python:3.10-bullseye
# Set the timezone to PST (America/Los_Angeles)
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update -qq && apt-get install ffmpeg -y
COPY requirements.txt requirements.txt
COPY main.py videosage.py
COPY .env .env
RUN pip3 install -r requirements.txt --progress-bar off
EXPOSE 8080
CMD ["python", "-u", "/api/videosage.py"] 